;==============================================================================
; MOD player - Play routine
;------------------------------------------------------------------------------
; API
;==============================================================================

extern mod_playroutine_init
extern mod_playroutine_tick
extern mod_playroutine_get_channel_info
extern mod_playroutine_get_position_info
extern mod_playroutine_get_position
extern mod_playroutine_set_position
