;==============================================================================
; MOD player - Software wavetable
;------------------------------------------------------------------------------
; API
;==============================================================================

extern mod_swt_setup
extern mod_swt_shutdown
extern mod_swt_upload_sample
extern mod_swt_free_sample
extern mod_swt_set_channels
extern mod_swt_set_amplify
extern mod_swt_set_interpolation
extern mod_swt_set_stereo_mode
extern mod_swt_reset_channels
extern mod_swt_set_sample
extern mod_swt_set_mixer
extern mod_swt_render
extern mod_swt_render_direct
extern mod_swt_get_mixer_info
