;==============================================================================
; System library - ISA DMA (Direct Memory Access) handling
;------------------------------------------------------------------------------
; API
;==============================================================================

%include "system/consts/public.inc"

extern sys_dma_disable_channel
extern sys_dma_enable_channel
extern sys_dma_setup_channel
