;==============================================================================
; System library - file handling operations
;------------------------------------------------------------------------------
; API
;==============================================================================

%include "system/consts/public.inc"

extern sys_file_setup
extern sys_file_shutdown
extern sys_file_open
extern sys_file_close
extern sys_file_read
extern sys_file_write
extern sys_file_set_pos
extern sys_file_get_pos
extern sys_file_get_size
extern sys_file_get_buf_addr
