;==============================================================================
; System library - memory handling operations
;------------------------------------------------------------------------------
; API
;==============================================================================

%include "system/consts/public.inc"

extern sys_mem_setup
extern sys_mem_shutdown
extern sys_mem_alloc
extern sys_mem_free
