;==============================================================================
; System library - PIT (Programmable Interval Timer) handling
;------------------------------------------------------------------------------
; API
;==============================================================================

%include "system/consts/public.inc"

extern sys_pit_calc_rate
extern sys_pit_set_irq0_rate
extern sys_pit_reset_irq0_rate
