;==============================================================================
; System library - string operations
;------------------------------------------------------------------------------
; API
;==============================================================================

extern sys_str_len
extern sys_str_reverse
extern sys_str_copy
extern sys_str_append
extern sys_str_char_pos
extern sys_str_cmp
extern sys_str_int
extern sys_str_fixed
extern sys_str_hex
extern sys_str_parse_int
extern sys_str_parse_hex
extern sys_str_parse_fixed
extern sys_str_format
extern sys_str_char_rpos
