;==============================================================================
; MOD player GUI
;------------------------------------------------------------------------------
; Global constants
;==============================================================================

FILL_UNROLL	EQU 4			; Video memory fill loop unrolls
MAX_FONT_HEIGHT	EQU 48			; Talles font size allowed
BUF_OFLOW_CHARS EQU 8			; Render buffer overflow bytes (even)