;==============================================================================
; MOD player GUI - Setup and initialization
;------------------------------------------------------------------------------
; API
;==============================================================================

%include "gui/consts/public.inc"

extern gui_setup
extern gui_shutdown
extern gui_plane_chars
extern gui_scr_width
extern gui_scr_height
extern gui_draw_box
extern gui_blit_bitmap
