;==============================================================================
; MOD player - DAC output device
;------------------------------------------------------------------------------
; Constants
;==============================================================================

; Buffer rendering status

BUF_READY	EQU 0
BUF_RENDERING	EQU 1
BUF_RENDER_1	EQU 2
BUF_RENDER_2	EQU 3
BUF_RENDER_3	EQU 4
